language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.11"
  - "nightly"  # nightly build
# command to install dependencies
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install --user -r requirements.txt
# command to run tests
script:
  - pytest
