# Generated by Django 4.2.8 on 2024-01-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="comment_karma",
        ),
        migrations.RemoveField(
            model_name="user",
            name="post_karma",
        ),
        migrations.AddField(
            model_name="user",
            name="karma",
            field=models.IntegerField(default=0),
        ),
    ]
