# Generated by Django 4.2.8 on 2024-01-03 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="author_name",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="url",
        ),
    ]
