# Generated by Django 4.2.8 on 2024-01-04 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_remove_submission_author_name_remove_submission_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author_name",
        ),
    ]
