# Generated by Django 4.2.8 on 2024-01-05 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_remove_comment_author_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="downs",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="score",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="ups",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="vote_object_id",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="vote_object_type",
        ),
        migrations.AddField(
            model_name="vote",
            name="comment",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="blog.comment"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="submission",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="blog.submission"),
        ),
        migrations.AlterField(
            model_name="vote",
            name="submission",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="blog.submission"),
        ),
    ]
