# Generated by Django 4.2.8 on 2024-01-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_remove_submission_downs_remove_submission_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
