# Generated by Django 4.2.8 on 2024-01-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_submission_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
